apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
    service: server
spec:
  ports:
  - name: https
    port: 8443
  selector:
    app: server
---
apiVersion: v1
kind: Secret
metadata:
  name: egress-server-cert
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREVENDQWZXZ0F3SUJBZ0lVZjA2YU5aS1FqeTUxWkV3NTdsL0pvenY2WDU0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tabXh2YldWemFDNXBiekFnRncweU16QTVNVFV4TURRd01qTmFHQTh6TURJegpNREV4TmpFd05EQXlNMW93RlRFVE1CRUdBMVVFQXd3S1pteHZiV1Z6YUM1cGJ6Q0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLYmFHRFIxUXBRUnlUKzQxWUtSNWxRQnZpbFoyQklJc1FXRHhCb0YKV1hPQzlTcGFEODVPVVI1aGQva1Z6eS85SzNpRmFuaTRTbW0xc01IR3lmRWdyK3pQTnV5TWY0OFNpRDZPd3U0NQo5eVoyL3g3dkNHUVh6V0FWNFF3emFVM2NDMCt4OU9XSVRaRHQrV3ZWdndCdERKYjRheTVPN3JzZDZmZEswWlBLCjRDZWhUdlU2am5lM2l4K3FFbGRjY253U0JMc0FscjhDOEpYanVZU3QrTmh3VVVKYnFvZHpvSTRnbEtqbG9qSDEKNHJGNFllSVlHcnE0TU13QjJPOWNMekdsRWFwQ0Y2NmYvOGtJMU1PaHlpTys1dDVadmljdmgrdG85RHNnR3IrdwpCcms3eFpMR2xQcFdXRkhYMjFsS0wwOS9XUVNFZy9uY1RodjdzajUyTHc5RjFza0NBd0VBQWFOVE1GRXdIUVlEClZSME9CQllFRk05YjdwajFrOGE1N3lJemdBb2IrdDFFQkl3dU1COEdBMVVkSXdRWU1CYUFGTTliN3BqMWs4YTUKN3lJemdBb2IrdDFFQkl3dU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQgpBQTd3ZS9IcVZaSnBjWEZuc3IzcHpCTlVYTVBxZ2xKZlNidFVmNTVJZ1R0TUs4NzhTYWJUc2lXRDU4K1hGNXlkCk5ZVGdSdmxWbDhHMXlZTGJLS1JQczFEOEllTzhjbjdHUHpZTUpuYmkzaVk0bGdUVlBSdm1TTmt2TDZzRTVXbnAKd3UyYlk5YTZDOFFQbnAyUGx2RDRTR2U1ZHlOdVg5bzdlYlluUWxpMlBJNlRnZUFnL3UyK3dqTkk4aXc5UkgySQo0OVZwRkkwWnhOWUEwQlNkYXZqcnlDOTVKcmU2RzNiV2ZMb3ArOTBmOUV6ZkxBZVlLWGFpZFlCTitaalVFai9MCkZnd0EzcjBnQ0liWXN5M1lTNmNQLzJGTWtRb3dkTzQzUGhaV3NTcXhMSU9yTGlJNFdodnhiR2Z1bGc5NEdXMDEKOTJhdlFYc0loSkxHSnVDRlVmeENVT2c9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUVENDQWpXZ0F3SUJBZ0lVWTc5SExyNG5USFIzK08rQXA5Rkw5U2JNVW1Bd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tabXh2YldWemFDNXBiekFlRncweU16RXhNVGN3T0RNNU1qaGFGdzB5T0RFeApNVFV3T0RNNU1qaGFNREV4THpBdEJnTlZCQU1NSm5ObGNuWmxjaTVsWjNKbGMzTXRjMlZ5ZG1WeUxuTjJZeTVqCmJIVnpkR1Z5TG14dlkyRnNNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZEdHgKdXBWRXYzZzV2SjBXenZKdHhJVTJpa2dTbUpHOUYzV2RhOU5palZFUmEvaThQUGloNmdjVkQ1NUtxUTZXV0tZUgpuMm9ycTR6V0s5azVEbnFBbzhMeGFnbStRYVp0WFRZc3JxdGlEamRCMWNybFhONWFqa1d6THgzOUZEY0t0bVF4CjdzVGFuZFRhYmZrMzBLWktLNU9Id1UydjNsY2ZoZ09wZHBRbkFMdDB4aDhwdjBQM3kzdzBnRVczb21sMURyL1gKVjZtZUxyOXp1SGtGeXc2THhiUW4yRU5ic2UrVHpua1NLMWQyMjkrZlJaNVlERHdLb3M5Smd3Q2JHRGp5VHNMOApjb3JPd1pXWEg4akdQTU5qWmlJalN4Wjk2bmRyRWF1QlcvMHVGOUErbVZ2SHBXRVJLczlScWg2cnFkbVJmR0V6ClRKSFYyZkhhRDAxSDRVemdmd0lEQVFBQm8za3dkekFkQmdOVkhRNEVGZ1FVNVdwb0tVNGl3RXdKaDN3dFQ5VWEKdk5UTkJHWXdId1lEVlIwakJCZ3dGb0FVejF2dW1QV1R4cm52SWpPQUNodjYzVVFFakM0d0hRWURWUjBsQkJZdwpGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUFzR0ExVWREd1FFQXdJSGdEQUpCZ05WSFJNRUFqQUFNQTBHCkNTcUdTSWIzRFFFQkN3VUFBNElCQVFCc2lqMkRVT21FWStUaExhUE9yVk5aQmthSTlnb1JENG9tTVAzeXBiRzcKdFY3U0U0SW5zaXlObEhuNXFTcE4yWkJ2Mk1zRGZVclloY2huUUpRRjY2eU96N282ZGF3bFdhclg4djJkQWVybwo1TmtHdmQ5VVZpbE53cVA3c2wzNG5SUjU5N0xKdDlDQW1ZRHlyM2VDNXQ5aHB6THMveEwxRCsrQ1l4RC9rbk9OCjFDVGR5Z3VoLzJuT0I2UVlueExDRXpSbFFPYW1UUTlyakpSMU1mMXQxcExkaERWVXd5UUFhaE95ZS9kSHpzWlQKT0NqckczUW5zRTljcE9abEFIZExPMXVDeHB5a3B2TTQvY2Fpc2UxTEU2dkw0U2dic28vVG1TcnZOWTFVeC9DcgphMHdLeXRjOUhVU3dHUExCT3dFOGpFUnd3dXNhVlBXbHBZS1QzVVpZK2VsbQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQzhPM0c2bFVTL2VEbTgKblJiTzhtM0VoVGFLU0JLWWtiMFhkWjFyMDJLTlVSRnIrTHc4K0tIcUJ4VVBua3FwRHBaWXBoR2ZhaXVyak5ZcgoyVGtPZW9Dand2RnFDYjVCcG0xZE5peXVxMklPTjBIVnl1VmMzbHFPUmJNdkhmMFVOd3EyWkRIdXhOcWQxTnB0CitUZlFwa29yazRmQlRhL2VWeCtHQTZsMmxDY0F1M1RHSHltL1EvZkxmRFNBUmJlaWFYVU92OWRYcVo0dXYzTzQKZVFYTERvdkZ0Q2ZZUTF1eDc1UE9lUklyVjNiYjM1OUZubGdNUEFxaXowbURBSnNZT1BKT3d2eHlpczdCbFpjZgp5TVk4dzJObUlpTkxGbjNxZDJzUnE0RmIvUzRYMEQ2Wlc4ZWxZUkVxejFHcUhxdXAyWkY4WVROTWtkWFo4ZG9QClRVZmhUT0IvQWdNQkFBRUNnZ0VBQWd0RWlvOG1aa3lLNi9acUVmM2w4cFZlYUpWWEc3QmNINk5zL2QwWGNUWVQKMGdWVnlKKzJqN3V3bnpFaEx4YkpJU3RQS1FPcnpSQVpkSjV3Nm9HcXRmSGUvSlRMSzhhcWpMR1M2S1AvSU8wTwpyNkNsYWFNWEtWRUR4M0RlN1FKRlZvSmVCeHdTSWxhaERKZ0JPQ2g3YzdVRmExNzBRdk4vNmN6NUM4cnVFQ21lCjJsQzF2VGgwai9Xa01kekNWeEQzZlRmb2wxYXI0QkdaYlk5RFM5UmUzZ2dxK29SR0NPNkg4VTA4d2JrYUJtUTYKdWFuTi9aT0JiRDBkRm5NNmZydHljUUtYSUp3b0hvanorUWZ3UDZlQ25jbUNHT0NER0lnRGJra3U0TWNPZWRCTQo2YzdYYnhzV1VnWWFuYUFSMFdhNVNhUXpiSzFiQ01xdklua2FTOHpMb1FLQmdRRGlIRzg3UGgwK0ladTJoUExyClF4a2NjREQ4clNVd2E5SGd3VldBbEg2Z1NiVXlvZ1hteHI3MCtJY1NJVHFzaTg5bFV2bFZ1bGVZOSs0Q0h3anUKcGFndnRkOWhxU3A2c2thKzRVdURES1JiRS9tRDM0RnhsVW1OaFNvTkNySTBkTXdyRU1MMWNIRzNqdmhBUWVtdgpFMTdLTEEza1ZtRytsYkZPV1NIc2k0cnY3d0tCZ1FEVkhUSEZTQ0ExWUtrbzZDZXQyK2Z5b2VScWR2dW9tK2hiCi9ibVROWHVsRXhDelFjZkFCcTlKWnhaUGpUaVVUQ0tIcjR2VlZvS1p6dVlUM2loK3h3QVhOT0F5b3NpK2h4R0MKaEU2RXJ2THQ5RmpkMzI2d0cvSE9WVDl5YWNiOHJsNGFzRi9IVUhJaWFYSmJQekU2NDc2RWc3V2JvQ3lZODhhLwpWYTNsM0o2SWNRS0JnQkV2WWhEWm5yVmJMbytIdVVMQ1BjVllqWkNXeEUzUzFBZkdDZTZVMnE3cUN6aUc4ZlhoClF5QXhSMnJNVmI1SmZnRFFkcHphWmMvOWYveHZTV21CODY5MG5qNjQ4YjZUa0NidnpxSnVNb3V0ai9oQzQzNnoKZnZ5ZmsxdWNaWUR4STVkZVZjTDd3ZGpXcCsyU1ZPVjJqbXpGUG1VTlg2NXhpQ0ZSU3UvRWgxSEhBb0dBTks2Lwo0LzRkZ0RTQi9NdlBLMHFHZjFPSURNMlhEcXBqK1lHeWczS2dPMEdJU2xnRGtqUFUxemQxcTNyRXR0eFBXTzJMCml0U1Urb0xNRzdNNm5ZU0NRRHBoQmdONXpxZkRLMW1iczI4d1BLUy81ekZad28xVjdHVGtoMXNneHN3d0ZUYnUKcG0zN21RZ3FMZVprUENPYXNGV0M2cExoRTNxSDhqcXkvM1RYZC9FQ2dZQUhwKytWQ29ZMUJHSXZDSGdTZExXMQpmaFJRSTM5WVhBVVJ6S1NpNnZGYWppQXNxaVZKblZodnZxREFEeEhodlJ6eUMxRVZESWl1dmdqOEQ1SzlIS1kvCjM5d3BZaGFGdWhNMFdvV3NQS1k1U0JzdkhtOGxaRGNuR2JrdDVxZlpHYkU0SmEzejRDUERYbFp2V3ZIaytlSWkKMmZOaCttVHl1bDFHOHpTc0xMNE9pUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: server
      containers:
      - image: cybwan/mtls-egress-demo-server
        imagePullPolicy: Always
        name: server
        command: ["/server"]
        ports:
        - containerPort: 8443
        volumeMounts:
          - name: egress-server-cert
            mountPath: /certs
      volumes:
        - name: egress-server-cert
          secret:
            secretName: egress-server-cert
